debug = true
[tracker]
listen_address = "0.0.0.0:8001"
shutdown_timeout = 5000
[database]
dsn = "efes:123@(efes_mysql_1:3306)/efes"
[server]
datadir = "/srv/efes/dev1"
listen_address_for_read = "0.0.0.0:8500"
listen_address = "0.0.0.0:8501"
shutdown_timeout = 10000
clean_disk_file_ttl = 60
clean_disk_run_period = 30
[amqp]
url = "amqp://efes:123@efes_rabbitmq_1:5672/"
[client]
tracker_url = "http://efes_tracker_1:8001"
chunk_size = "1M"
